module.exports = {
    "#": "№",
    "new project": "новый проект",
    "Title": "Заголовок",
    "edit": "редактировать", 
    "Projects": "Проекты", 
    "List of projects": "Перечень проектов", 
    "My Projects": "Мои проекты", 
    "Select a project": "Выберите проект", 
    "Projects are empty. Please add some projects using control panel!": "Нет проектов. Пожалуйста, добавьте проекты используя панель администратора!", 
    "Description": "Описание",
    "Short description": "Краткое описание", 
    "Thumbnail": "Изображение", 
    "edit": "редактировать",
    "delete": "удалить",
    "Select file": "Выбрать файл",
    "field is required": "обязательное поле",
    "Image": "Изображение",
    "Text": "Текст",
    "Save project": "Сохранить проект",
    "Create project": "Добавить проект",
    "Show first title": "Заголовок",
    "Show second title": "Подзаголовок",
    "Show image": "Показывать изображение",
    "Show name": "Название",
    "Show description": "Описание",
    "Show case button": "Кнопка кейса",
    "Button text:": "Текст кнопки:",
    "Background color:": "Цвет фона:"
}